### ISSUE TITLE
Compute summary metrics

### ISSUE THREAD

**Issue by lidefi87** [aodn/IMOS-hackathon#32]
Calculations per tag/individual per day
- [x] Distance travelled (cumulative)
- [x] Distance travelled (daily)
- [x] Depth summaries (min, mean, maximum, etc.)
- [x] Temperature summaries (min, mean, maximum, etc.)
- [x] Distance to shelf (200 meter depth)
- [x] Distance to shore
- [x] Maximum depth at each position (sea floor depth)

**Comment by Jiayingabbyguo** [comment]
Summary_metrics_depth_temp.R summarize the daily depth and temperature profile.
